### ISSUE TITLE
좋아요 취소 테스트의 NPE 오류

### ISSUE THREAD

**Issue by jiaeYoon** [jiaeYoon/Booklog#17]
## Describe the bug
좋아요 취소 테스트 진행을 위해 선행된 좋아요 등록 과정 中
게시글의 좋아요 수 업데이트 중 게시글의 좋아요 수가 null로 조회되며 NullPointerException 발생

## To Reproduce
1. Go to `LikesServiceTest.java`
2. Click on `좋아요_취소 테스트`
3. See error

## Expected behavior
좋아요 등록 후 좋아요를 취소하며 'LikesRepository 사이즈'는 '좋아요 등록된 LikesRepository 사이즈 -1'과 같음

## Screenshots or Error Log
```
[LikesServiceTest.java]
class LikesServiceTest {
    @Test
    void 좋아요_취소() {
    
        //given
        Long postId = postService.save(new PostRequestDto(...));
        
        //when
        Long likesId = likesService.save(postId, new LikesSaveRequestDto(user1.getId(), postId)); 
        ...
    }
}

[LikesService.java]
public class LikesService {
    public Long save(Long postId, LikesSaveRequestDto requestDto) {
        ...  
        post.updateLikesCnt(post.getLikesCnt());    // NullPointerException 발생
        ...
    }
}
```

```
Hibernate: insert into user (created_at, updated_at, email, join_type, name, nickname, password) values (?, ?, ?, ?, ?, ?, ?)
Hibernate: insert into post (book_title, book_writer, content, post_at, post_title, rating, read_end, read_start, user_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)

java.lang.NullPointerException
	at kr.org.booklog.domain.post.entity.Post.updateLikesCnt(Post.java:83)
	at kr.org.booklog.domain.like.service.LikesService.save(LikesService.java:39)
	...
	at kr.org.booklog.domain.likes.service.LikesServiceTest.좋아요_취소(LikesServiceTest.java:90)
```

## Spring Project Setting:
 - Version 2.7.11
 - Gradle 8.1.1
- Java 11

**Comment by jiaeYoon** [comment]
**오류 발생 원인 추측** 
게시글을 등록하는 postService.save에서 게시글 DB에 저장하는 부분인 requestDto.toEntity()에 좋아요, 댓글 수를 명시적으로 저장하지 않음

**오류 해결**
게시글 등록하는 PostRequestDto 클래스의 toEntity 메소드에 likesCnt, commentsCnt 값을 0으로 명시하여 Post 객체 생성
```
public class PostRequestDto {
    public Post toEntity() {
        return Post.builder()
            ...
            .likesCnt(0)
            .commentsCnt(0)
            .build();
    }
}
```

**Comment by jiaeYoon** [comment]
**의문**
Post Entity에서 좋아요, 댓글 수의 디폴트 값을 @ColumnDefault("0")로 설정했는데 
좋아요, 댓글 수가 0으로 자동 저장되지 않는 이유?

**원인 파악**
테스트 코드의 `@Transactional`이 디폴트 값의 적용을 방해하는 것으로 보임
```
@Test
void 좋아요_취소() {

    //given
    Long postId = postService.save(new PostRequestDto(...));

    Post result = postRepository.findById(postId)
            .orElseThrow(() -> new IllegalArgumentException("no post. id = " + postId));

    System.out.println("likes count :" + result.getLikesCnt());

}
```

테스트 코드에 `@Transactional`을 적용한 경우
- findById에 의한 select 쿼리 실행 안됨
- getLikesCnt() 결과, null 반환
```
Hibernate: insert into post (book_title, book_writer, content, post_at, post_title, rating, read_end, read_start, user_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
likes count :null
```

테스트 코드에 `@Transactional`을 적용하지 않은 경우
- findById에 의한 select 쿼리 실행
- getLikesCnt() 결과, 0 반환
```
Hibernate: insert into post (book_title, book_writer, content, post_at, post_title, rating, read_end, read_start, user_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
Hibernate: select post0_.id as id1_2_0_, post0_.book_title as book_tit2_2_0_, post0_.book_writer as book_wri3_2_0_, post0_.comments_cnt as comments4_2_0_, post0_.content as content5_2_0_, post0_.likes_cnt as likes_cn6_2_0_, post0_.post_at as post_at7_2_0_, post0_.post_title as post_tit8_2_0_, post0_.rating as rating9_2_0_, post0_.read_end as read_en10_2_0_, post0_.read_start as read_st11_2_0_, post0_.user_id as user_id12_2_0_ from post post0_ where post0_.id=?
likes count :0
```

**Comment by jiaeYoon** [comment]
**일시적 해결**
LikesServiceTest는 `@Transactional` 없이 실행할 것
실행 후엔 수동으로 데이터베이스를 롤백하도록 한다.
